<script>



function printPdf(){
    // url to print PDF    
    var urlPDF = '<?php echo $this->getPrintUrl(); ?>';
    document.location.href = (urlPDF);
} 

function notifyCustomer(){
    // url to notify the customer (ask him to create vimesso)
    var urlNotify = '<?php echo $this->getNotifyUrl(); ?>';
    document.location.href = (urlNotify);
}

</script>


<?php if (!$this->orderContainsVimesso()): ?>
    <p><?php echo $this->__('No Vimesso for this order'); ?><br /></p>
<?php elseif (!$this->isVimessoOnline() || !$_vimesso = $this->getVimesso()): ?>
    <p><?php echo $this->__('Vimesso is offline, please try later.'); ?><br /></p>
<?php else: ?>
    
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Vimesso Settings');  ?></h4>
    </div> 
    <div id="div-form" name="div-form"  class="fieldset fieldset-wide">
        <div class="hor-scroll">

           <fieldset>
            <div style="margin-bottom: 15px; margin-top: ">
                <table cellspacing="25px">
                    <tr>
                        <td><button type="button" class="scalable" onclick="printPdf();" style=""><span><?php echo $this->__('Print'); ?></span></button></td>
                        <td><button type="button" class="scalable" onclick="notifyCustomer();" style=""><span><?php echo $this->__('Notify Customer'); ?></span></button></td>
                    </tr>
                </table>
            </div>
           </fieldset>
            
           <fieldset>
                <table class="form-list">
                    <tbody>
                        <tr>
                            <td class="label" width="20%">
                               <h2>Reading settings</h2>
                                <p>
                                    <h3><?php echo $this->__('Vimesso code : %s', $_vimesso->getCode()); ?></h3>
                                    <img src="<?php echo $_vimesso->getRqr(); ?>" />
                                    <br /> 
                                    <font face=arial size=2>
                                        <a href="<?php echo $_vimesso->getReadLinkForVimesso(); ?>" target="_blank">
                                        <font><?php echo $this->__('Click here to view the vimesso'); ?></font></a> 
                                    </font>
                                </p>
                             </td>
                             <td class="label">
                                  <h2>Creating settings</h2>
                                   <p>
                                       <h3>&nbsp;</h3>
                                       <img src="<?php echo $_vimesso->getCqr(); ?>" />
                                       <br />
                                    <font face=arial size=2>
                                        <a href="<?php echo $_vimesso->getCreationLinkForVimesso(); ?>" target="_blank">
                                        <font><?php echo $this->__('Click here to create the vimesso'); ?></font></a> 
                                    </font>
                                   </p>
                             </td>
                           
                        </tr>  
                </table>
            </fieldset>
        </div>
   </div>
<?php endif; ?>
